src/Entity/User.php
<?php

namespace KarlitoWeb\Users\Entity;

use KarlitoWeb\Users\Repository\UserRepository;
use DateTimeImmutable;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\Persistence\Event\LifecycleEventArgs;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Uid\Uuid;

/**
 * Class User
 *
 * @package KarlitoWeb\Users\Entity
 */
#[ORM\Entity(repositoryClass: UserRepository::class)]
#[ORM\HasLifecycleCallbacks]
#[ORM\Table(name: 'account_user')]
#[UniqueEntity(fields: 'email', message: 'There is alrealdy an account with this {{ label }} in DataBase')]
#[UniqueEntity(fields: 'username', message: 'There is alrealdy an account with this {{ label }} in DataBase')]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
	#[ORM\Id]
	#[ORM\GeneratedValue]
	#[ORM\Column(type: 'integer', options: ['unsigned' => true])]
	private ?int $id = null;

	#[ORM\Column(type: 'string', length: 180, unique: true)]
	#[Assert\Uuid(strict: true)]
	private ?string $uuid = null;

	#[ORM\Column(type: 'string', length: 64, nullable: true, options: ['default' => null])]
	#[Assert\Length(min: 0, max: 64)]
	#[Assert\Type('string')]
	private ?string $username = null;

	#[ORM\Column(type: 'string', length: 255, nullable: false)]
	#[Assert\Email]
	#[Assert\Length(min: 8, max: 255)]
	#[Assert\Type('string')]
	private string $email;

	#[ORM\Column(type: 'string', length: 64, nullable: true, options: ['default' => null])]
	#[Assert\Length(min: 0, max: 64)]
	#[Assert\Type('string')]
	private ?string $firstname = null;

	#[ORM\Column(type: 'string', length: 60, nullable: true, options: ['default' => null])]
	#[Assert\Length(min: 0, max: 64)]
	#[Assert\Type('string')]
	private ?string $lastname = null;

	#[ORM\Column(type: 'json')]
	#[Assert\NotNull]
	private array $roles = [];

	/**
	 * @var ?string The hashed password
	 */
	#[ORM\Column(type: 'string', length: 255, nullable: true, options: ['default' => null])]
	#[Assert\Length(min: 8, max: 255)]
	#[Assert\Type('string')]
	private ?string $password = null;

	private ?string $plainPassword = null;

	#[ORM\Column(type: 'boolean', options: ['default' => false])]
	private bool $isVerified = false;

	#[ORM\Column(type: 'string', length: 255, nullable: true, options: ['default' => null])]
	private ?string $githubId = null;

	#[ORM\Column(type: 'string', length: 255, nullable: true, options: ['default' => null])]
	private ?string $googleId = null;

	#[ORM\Column(type: 'date_immutable')]
	#[Assert\NotNull]
	private DateTimeImmutable $createdAt;

	#[ORM\Column(type: 'date_immutable')]
	#[Assert\NotNull]
	private DateTimeImmutable $updatedAt;

	#[ORM\Column(type: 'date_immutable', nullable: true, options: ['default' => null])]
	private ?DateTimeImmutable $deletedAt = null;

	public function __construct()
	{
		$this->createdAt = new DateTimeImmutable();
		$this->updatedAt = new DateTimeImmutable();
		$this->setUuid();
	}

    public function __toString(): string
    {
        return $this->getFirstname() . ' ' . $this->getLastname();
    }


    public function getId(): ?int
	{
		return $this->id;
	}

	public function getUuid(): ?string
	{
		return $this->uuid;
	}

	public function setUuid(?string $uuid = null): static
	{
		if (is_null($uuid)) {
			$uuidGenerator = Uuid::v4();
			$this->uuid = $uuidGenerator->toRfc4122();
		} else {
			$this->uuid = $uuid;
		}

		return $this;
	}

	public function getUsername(): ?string
	{
		return $this->username;
	}

	public function setUsername(?string $username): static
	{
		$this->username = $username;

		return $this;
	}

	public function getEmail(): ?string
	{
		return $this->email;
	}

	public function setEmail(?string $email): static
	{
		$this->email = $email;

		return $this;
	}

	public function getFirstname(): ?string
	{
		return $this->firstname;
	}

	public function setFirstname(?string $firstname): static
	{
		$this->firstname = $firstname;

		return $this;
	}

	public function getLastname(): ?string
	{
		return $this->lastname;
	}

	public function setLastname(?string $lastname): static
	{
		$this->lastname = $lastname;

		return $this;
	}

	/**
	 * A visual identifier that represents this user.
	 *
	 * @see UserInterface
	 */
	public function getUserIdentifier(): string
	{
		return (string) $this->uuid;
	}

	/**
	 * @see UserInterface
	 */
	public function getRoles(): array
	{
		$roles = $this->roles;
		// guarantee every user at least has ROLE_USER
		$roles[] = 'ROLE_USER';

		return array_unique($roles);
	}

	public function setRoles(array $roles): static
	{
		$this->roles = $roles;

		return $this;
	}

	/**
	 * @see PasswordAuthenticatedUserInterface
	 */
	public function getPassword(): string
	{
		return $this->password;
	}

	public function setPassword(string $password): static
	{
		$this->password = $password;

		return $this;
	}

	public function getPlainPassword(): ?string
	{
		return $this->plainPassword;
	}

	public function setPlainPassword(?string $plainPassword): static
	{
		$this->plainPassword = $plainPassword;

		return $this;
	}

	/**
	 * Returning a salt is only needed if you are not using a modern
	 * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
	 *
	 * @see UserInterface
	 */
	public function getSalt(): ?string
	{
		return null;
	}

	/**
	 * @see UserInterface
	 */
	public function eraseCredentials(): void
	{
		// If you store any temporary, sensitive data on the user, clear it here
		// $this->plainPassword = null;
	}

	public function isVerified(): bool
	{
		return $this->isVerified;
	}

	public function setIsVerified(bool $isVerified): static
	{
		$this->isVerified = $isVerified;

		return $this;
	}

    public function getGithubId(): ?string
    {
        return $this->githubId;
    }

    public function setGithubId(?string $githubId): static
    {
        $this->githubId = $githubId;

        return $this;
    }

    public function getGoogleId(): ?string
    {
        return $this->googleId;
    }

    public function setGoogleId(?string $googleId): static
    {
        $this->googleId = $googleId;

        return $this;
    }

	public function getCreatedAt(): ?DateTimeImmutable
	{
		return $this->createdAt;
	}

	public function setCreatedAt(DateTimeImmutable $createdAt): static
	{
		$this->createdAt = $createdAt;

		return $this;
	}

	public function getUpdatedAt(): ?DateTimeImmutable
	{
		return $this->updatedAt;
	}

	public function setUpdatedAt(DateTimeImmutable $updatedAt): static
	{
		$this->updatedAt = $updatedAt;

		return $this;
	}

	public function getDeletedAt(): ?DateTimeImmutable
	{
		return $this->deletedAt;
	}

	public function setDeletedAt(?DateTimeImmutable $deletedAt): static
	{
		$this->deletedAt = $deletedAt;

		return $this;
	}

    /**
     * @param LifecycleEventArgs $args
     * @return void
     */
    #[ORM\PreUpdate]
    public function preUpdate(LifecycleEventArgs $args): void
    {
        /* @var User $object */
        $object = $args->getObject();
        if ($object instanceof User) {
            $object->setUpdatedAt(new \DateTimeImmutable('now'));
        }
    }
}

src/Controller/DashboardController.php
<?php

namespace KarlitoWeb\Users\Controller;

use KarlitoWeb\Users\DTO\UserSearch;
use KarlitoWeb\Users\Form\SearchUserType;
use KarlitoWeb\Users\Repository\UserRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * Class DashboardController
 *
 * @package KarlitoWeb\Users\Controller
 */
#[Route(path: '/users', name: 'kw.users.dashboard.', methods: ['GET'], format: 'html', utf8: true)]
final class DashboardController extends AbstractController
{
	#[Route(path: '/dashboard.php', name: 'index', options: ['expose' => true])]
	public function index(Request $request): Response
	{
        $r = new UserSearch();
        $form = $this->createForm(SearchUserType::class, $r)->handleRequest($request);

		return $this->render('@Users/contents/dashboard/index.html.twig', [
			'controller_name' => 'Welcome to Dashboard Users',
			'form'            => $form->createView(),
		]);
	}

    /**
     * Interroge la BDD pour récupérer un utilisateur
     */
    #[Route('/search.php', name: 'search', methods: ['POST'])]
    public function search(Request $request, UserRepository $repository): Response
    {
        /**
         * Récupère la valeur de la requête
         *
         * @var string $search
         */
        $search = $request->request->get('search');

        if (strlen($search) < 2) {
            return $this->render('@Users/contents/dashboard/_search.html.twig', [
                'search' => $repository->findBy([]),
            ]);
        } else {
            return $this->render('@Users/contents/dashboard/_search.html.twig', [
                'search' => $repository->findUserBySearch($search),
            ]);
        }
    }
}

templates/contents/dashboard/_search.html.twig
{% if search is defined %}
    {% for user in search %}
    <tr>
        <th scope="row" class="text-center fw-normal">{{ loop.index }}</th>
        <td class="fw-bolder">{{ user.username }}</td>
        <td class="fw-bolder">{{ user.firstname }}</td>
        <td class="fw-bolder">{{ user.lastname }}</td>
        <td class="fw-bolder">{{ user.email }}</td>
        <td class="text-center">{% if user.verified is empty %}<i class="fa-solid fa-square-xmark text-danger fa-2x"></i>{% else %}<i class="fa-solid fa-square-check text-success fa-2x"></i>{% endif %}</td>
        <td class="text-end"><a href="{{ path('kw.users.profile.update', {'uuid': user.uuid}) }}"><i class="fa-regular fa-address-card fa-2x"></i></a></td>
    </tr>
    {% endfor %}
{% endif %}

templates/contents/dashboard/index-bootstrap.html.twig
{% extends '@Layouts/themes/niceadmin/bases/full.html.twig' %}

{% block contents %}

<div class="container">
    {% for flash_error in app.flashes('verify_email_error') %}
        <div class="alert alert-danger" role="alert">{{ flash_error }}</div>
    {% endfor %}

    {% include '@Users/contents/security/not-verified.html.twig' %}

    <h1 class="text-white-50 shadow mb-3 pb-3 border-1 border-bottom">{{ controller_name }}</h1>

    <table class="table">
        <thead>
            <tr>
                <th scope="col" class="text-center">#</th>
                <th scope="col">Username</th>
                <th scope="col">Firstname</th>
                <th scope="col">Lastname</th>
                <th scope="col">Email</th>
                <th scope="col" class="text-center">Verified</th>
                <th scope="col" class="text-end">Profile</th>
            </tr>
        </thead>
        <tbody id="search-results"></tbody>
{#        <tbody>#}
{#            {% for user in users %}#}
{#            <tr>#}
{#                <th scope="row" class="text-center">{{ loop.index }}</th>#}
{#                <td>{{ user.username }}</td>#}
{#                <td>{{ user.firstname }}</td>#}
{#                <td>{{ user.lastname }}</td>#}
{#                <td>{{ user.email }}</td>#}
{#                <td class="text-center">{% if user.verified is empty %}<i class="fa-solid fa-square-xmark text-danger fa-2x"></i>{% else %}<i class="fa-solid fa-square-check text-success fa-2x"></i>{% endif %}</td>#}
{#                <td class="text-end"><a href="{{ path('kw.users.profile.update', {'uuid': user.uuid}) }}"><i class="fa-regular fa-address-card fa-2x"></i></a></td>#}
{#            </tr>#}
{#            {% endfor %}#}
{#        </tbody>#}
    </table>

</div>

{% endblock %}

{% block javascripts %}
    {{ parent() }}
    <script src="https://unpkg.com/htmx.org@2.0.4" integrity="sha384-HGfztofotfshcF7+8n44JQL2oJmowVChPTg48S+jvZoztPfvwD79OC/LTtG6dMp+" crossorigin="anonymous"></script>

{% endblock %}

{% block header %}{% include '@Users/partials/header.html.twig' with {'form': form} only %}{%- endblock %}

{% block sidebar %}{% include '@Users/partials/sidebar.html.twig' %}{% endblock %}

{% block favicons %}{% include '@Users/partials/favicon.html.twig' %}{% endblock %}

{% block title %}{{ controller_name }}{% endblock %}

templates/contents/dashboard/index.html.twig
{% extends '@Layouts/themes/niceadmin/bases/full.html.twig' %}

{% block contents %}

<main id="main" class="main">
    <div class="pagetitle">
        <h1>Dashboard</h1>
        <nav>
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{{ path('kw.users.dashboard.index') }}">Home</a></li>
                <li class="breadcrumb-item active">Dashboard</li>
            </ol>
        </nav>
    </div><!-- End Page Title -->
    <section class="section dashboard">
        <div class="row">


{% for flash_error in app.flashes('verify_email_error') %}
    <div class="alert alert-danger" role="alert">{{ flash_error }}</div>
{% endfor %}

{% include '@Users/contents/security/not-verified.html.twig' %}

            <div class="card">
                <div class="card-header"> <h1 class="card-title p-0 mb-0">{{ controller_name }}</h1> </div>
                <div class="card-body">
                    <table class="table">
                        <thead>
                            <tr>
                                <th scope="col" class="text-center">#</th>
                                <th scope="col">Username</th>
                                <th scope="col">Firstname</th>
                                <th scope="col">Lastname</th>
                                <th scope="col">Email</th>
                                <th scope="col" class="text-center">Verified</th>
                                <th scope="col" class="text-end">Profile</th>
                            </tr>
                        </thead>
                        <tbody id="search-results"></tbody>
                {#        <tbody>#}
                {#            {% for user in users %}#}
                {#            <tr>#}
                {#                <th scope="row" class="text-center">{{ loop.index }}</th>#}
                {#                <td>{{ user.username }}</td>#}
                {#                <td>{{ user.firstname }}</td>#}
                {#                <td>{{ user.lastname }}</td>#}
                {#                <td>{{ user.email }}</td>#}
                {#                <td class="text-center">{% if user.verified is empty %}<i class="fa-solid fa-square-xmark text-danger fa-2x"></i>{% else %}<i class="fa-solid fa-square-check text-success fa-2x"></i>{% endif %}</td>#}
                {#                <td class="text-end"><a href="{{ path('kw.users.profile.update', {'uuid': user.uuid}) }}"><i class="fa-regular fa-address-card fa-2x"></i></a></td>#}
                {#            </tr>#}
                {#            {% endfor %}#}
                {#        </tbody>#}
                    </table>
                </div>
            </div>

        </div>
    </section>
</main>
<!-- End #main -->

{% endblock %}

{% block stylesheets %}
    {{ parent() }}
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@6.7.2/css/fontawesome.min.css">
    <style>
        table.table tr td, table.table tr th { padding: 0 8px; line-height: 40px; vert-align: middle; }
        table.table tr td svg { padding-top: 4px; }
    </style>

{% endblock %}

{% block javascripts %}
    {{ parent() }}
    <script src="https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@6.7.2/js/all.min.js"></script>
    <script src="https://unpkg.com/htmx.org@2.0.4" integrity="sha384-HGfztofotfshcF7+8n44JQL2oJmowVChPTg48S+jvZoztPfvwD79OC/LTtG6dMp+" crossorigin="anonymous"></script>

{% endblock %}

{% block header %}{% include '@Users/partials/header.html.twig' with {'form': form} only %}{%- endblock %}

{% block sidebar %}{% include '@Users/partials/sidebar.html.twig' %}{% endblock %}

{% block favicons %}{% include '@Users/partials/favicon.html.twig' %}{% endblock %}

{% block title %}{{ controller_name }}{% endblock %}